apiVersion: v1
kind: Service
metadata:
  name: yarp-proxy-net6-service
spec:
  type: LoadBalancer
  selector:
    app: yarp-proxy-net6
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000